# Generated by Django 4.2.27 on 2025-12-07 20:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person in the expense group (must be unique).', max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email address (for information only, not for login).', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Short description of what this expense was for.', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total expense amount (must be greater than 0).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date when the expense happened.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically set when the expense is created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp automatically updated when the expense is changed.')),
                ('paid_by', models.ForeignKey(help_text='Person who actually paid this expense.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to='expenses.person')),
                ('participants', models.ManyToManyField(help_text='People who share this expense. The amount is split equally.', related_name='expenses_participated', to='expenses.person')),
            ],
        ),
    ]
