# Generated by Django 4.2.27 on 2025-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_owner_person_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Name of the person in the expense group (must be unique).', max_length=100),
        ),
    ]
